import { EntityConfig } from "./types";

export const entityConfigs: Record<string, EntityConfig> = {
  news: {
    table: "news",
    title: "News",
    listColumns: [
      { key: "id", label: "ID", type: "text" },
      { key: "image_src", label: "Rasm", type: "image" },
      { key: "title", label: "Sarlavha", type: "text" },
      { key: "date_display", label: "Sana", type: "text" },
      { key: "slug", label: "Slug", type: "text" },
      { key: "link_text", label: "Havola matni", type: "text" },
      { key: "link_url", label: "Havola URL", type: "url" },
    ],
    formFields: [
      { key: "title", label: "Sarlavha", type: "text", required: true, min: 3 },
      {
        key: "slug",
        label: "Slug",
        type: "text",
        required: true,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      },
      { key: "description", label: "Tavsif", type: "richtext" },
      {
        key: "date_display",
        label: "Sana (matn)",
        type: "text",
        placeholder: "2025-yil 24-iyun",
      },
      {
        key: "image_src",
        label: "Rasm manzili",
        type: "imageOrUpload",
        folder: "news",
      },
      {
        key: "content",
        label: "Batafsil kontent",
        type: "richtext",
        helper: "Yangilik matni.",
      },
      {
        key: "gallery_images",
        label: "Galeriya rasmlari",
        type: "galleryImages",
        folder: "news",
        helper:
          "Rasmlarni birma-bir yuklang, ularni o'chirish va tartibini o'zgartirish mumkin",
      },
      {
        key: "video_src",
        label: "Video manzili",
        type: "text",
        placeholder: "/videos/news.mp4",
      },
      {
        key: "poster_src",
        label: "Video poster manzili",
        type: "imageOrUpload",
        folder: "news",
      },
      { key: "link_text", label: "Havola matni", type: "text" },
      { key: "link_url", label: "Havola URL", type: "url" },
    ],
    filters: [{ type: "date_display" }],
  },
  international_news: {
    table: "international_news",
    title: "International News",
    listColumns: [
      { key: "id", label: "ID", type: "text" },
      { key: "image_src", label: "Rasm", type: "image" },
      { key: "title", label: "Sarlavha", type: "text" },
      { key: "date_display", label: "Sana", type: "text" },
      { key: "slug", label: "Slug", type: "text" },
    ],
    formFields: [
      { key: "title", label: "Sarlavha", type: "text", required: true, min: 3 },
      {
        key: "slug",
        label: "Slug",
        type: "text",
        required: true,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      },
      { key: "description", label: "Tavsif", type: "richtext" },
      {
        key: "date_display",
        label: "Sana (matn)",
        type: "text",
        placeholder: "2025-yil 24-iyun",
      },
      {
        key: "image_src",
        label: "Rasm manzili",
        type: "imageOrUpload",
        folder: "intl",
      },
      {
        key: "content",
        label: "Batafsil kontent",
        type: "richtext",
        helper: "Yangilik matni.",
      },
      {
        key: "gallery_images",
        label: "Galeriya rasmlari",
        type: "galleryImages",
        folder: "intl",
        helper:
          "Rasmlarni birma-bir yuklang, ularni o'chirish va tartibini o'zgartirish mumkin",
      },
      { key: "link_text", label: "Havola matni", type: "text" },
      { key: "link_url", label: "Havola URL", type: "url" },
    ],
    filters: [{ type: "date_display" }],
  },
  projects: {
    table: "projects",
    title: "Projects",
    listColumns: [
      { key: "id", label: "ID", type: "text" },
      { key: "image_src", label: "Rasm", type: "image" },
      { key: "title", label: "Sarlavha", type: "text" },
      { key: "status", label: "Status", type: "text" },
      { key: "slug", label: "Slug", type: "text" },
    ],
    formFields: [
      { key: "title", label: "Sarlavha", type: "text", required: true },
      {
        key: "slug",
        label: "Slug",
        type: "text",
        required: true,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["Faol", "Yakunlangan", "Tez kunda"],
        required: true,
      },
      { key: "description", label: "Qisqa tavsif", type: "richtext" },
      {
        key: "content",
        label: "Batafsil kontent",
        type: "richtext",
        helper: "Loyiha haqida batafsil ma'lumot.",
      },
      {
        key: "image_src",
        label: "Rasm manzili",
        type: "imageOrUpload",
        folder: "projects",
      },
      {
        key: "video_src",
        label: "Video manzili",
        type: "text",
        placeholder: "/videos/project.mp4",
      },
      {
        key: "poster_src",
        label: "Poster rasm manzili",
        type: "imageOrUpload",
        folder: "projects",
      },
      {
        key: "current_step",
        label: "Joriy qadam",
        type: "text",
        placeholder: "9",
      },
      {
        key: "instagram_url",
        label: "Instagram URL",
        type: "url",
        placeholder: "https://www.instagram.com/...",
      },
      {
        key: "youtube_url",
        label: "YouTube URL",
        type: "url",
        placeholder: "https://youtube.com/@...",
      },
      {
        key: "telegram_url",
        label: "Telegram URL",
        type: "url",
        placeholder: "https://t.me/...",
      },
      {
        key: "facebook_url",
        label: "Facebook URL",
        type: "url",
        placeholder: "https://facebook.com/...",
      },
    ],
    filters: [{ type: "status" }],
  },
  contests: {
    table: "contests",
    title: "Contests",
    listColumns: [
      { key: "id", label: "ID", type: "text" },
      { key: "image_src", label: "Rasm", type: "image" },
      { key: "title", label: "Sarlavha", type: "text" },
      { key: "status", label: "Status", type: "text" },
      { key: "deadline", label: "Muddat", type: "text" },
      { key: "slug", label: "Slug", type: "text" },
    ],
    formFields: [
      { key: "title", label: "Sarlavha", type: "text", required: true },
      {
        key: "slug",
        label: "Slug",
        type: "text",
        required: true,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      },
      {
        key: "status",
        label: "Status",
        type: "select",
        options: ["Faol", "Yakunlangan"],
        required: true,
      },
      {
        key: "deadline",
        label: "Muddat (matn)",
        type: "text",
        placeholder: "Muddat: 2025-yil 3-noyabr",
      },
      { key: "description", label: "Qisqa tavsif", type: "richtext" },
      {
        key: "image_src",
        label: "Rasm manzili",
        type: "imageOrUpload",
        folder: "contests",
      },
      {
        key: "video_src",
        label: "Video manzili",
        type: "text",
        placeholder: "/videos/contest.mp4",
      },
      {
        key: "content_blocks",
        label: "Kontent bloklari",
        type: "contentBlocks",
        helper: "Tanlov matni, shartlari va boshqa bo'limlar uchun",
      },
      {
        key: "application_link",
        label: "Ariza fayli yoki havolasi",
        type: "fileOrUpload",
        folder: "contests",
        helper:
          "PDF fayl yuklang yoki havola kiriting. Agar ariza mavjud bo'lmasa uni bo'sh qoldiring!",
      },
      {
        key: "show_requirements",
        label: "Talablarni ko'rsatish",
        type: "checkbox",
        helper: "Tanlov talablarini sahifada ko'rsatish",
      },
    ],
    filters: [{ type: "status" }],
  },
  announcements: {
    table: "announcements",
    title: "Announcements",
    listColumns: [
      { key: "id", label: "ID", type: "text" },
      { key: "title", label: "Sarlavha", type: "text" },
      { key: "email", label: "Email", type: "email" },
      { key: "slug", label: "Slug", type: "text" },
    ],
    formFields: [
      { key: "title", label: "Sarlavha", type: "text", required: true },
      {
        key: "slug",
        label: "Slug",
        type: "text",
        required: true,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
        helper: "Faqat kichik harflar, raqamlar va tire ishlating.",
      },
      { key: "description", label: "Tavsif", type: "richtext" },
      { key: "email", label: "Email", type: "email" },
      { key: "date_display", label: "Muddat", type: "text" },
      { key: "content", label: "To‘liq matn (HTML)", type: "richtext" },
      { key: "footer_text", label: "Pastki matn", type: "richtext" },
    ],
  },
  analytics: {
    table: "analytics",
    title: "Analytics",
    listColumns: [
      { key: "id", label: "ID", type: "text" },
      { key: "image_src", label: "Rasm", type: "image" },
      { key: "date_display", label: "Sana", type: "text" },
      { key: "title", label: "Sarlavha", type: "text" },
      { key: "tag", label: "Teg", type: "text" },
      { key: "slug", label: "Slug", type: "text" },
    ],
    formFields: [
      { key: "title", label: "Sarlavha", type: "text", required: true, min: 3 },
      {
        key: "slug",
        label: "Slug",
        type: "text",
        required: true,
        pattern: "^[a-z0-9]+(?:-[a-z0-9]+)*$",
      },
      { key: "description", label: "Tavsif", type: "richtext" },
      {
        key: "tag",
        label: "Teg",
        type: "text",
        placeholder: "Kibersport",
      },
      {
        key: "date_display",
        label: "Sana (matn)",
        type: "text",
        placeholder: "2025-yil 24-iyun",
      },
      {
        key: "image_src",
        label: "Rasm manzili",
        type: "imageOrUpload",
        folder: "analytics",
      },
      {
        key: "content",
        label: "Batafsil kontent",
        type: "richtext",
        helper: "Analitika matni.",
      },
      {
        key: "gallery_images",
        label: "Galeriya rasmlari",
        type: "galleryImages",
        folder: "analytics",
        helper:
          "Rasmlarni birma-bir yuklang, ularni o'chirish va tartibini o'zgartirish mumkin",
      },
      {
        key: "video_src",
        label: "Video manzili",
        type: "text",
        placeholder: "/videos/analytics.mp4",
      },
      {
        key: "poster_src",
        label: "Video poster manzili",
        type: "imageOrUpload",
        folder: "analytics",
      },
    ],
    filters: [{ type: "date_display" }],
  },
};
